
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sculptor.Gynac.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class ModuleImage
{

    public ModuleImage()
    {

        this.UserModuleImages = new HashSet<UserModuleImage>();

    }


    public int Id { get; set; }

    public string SampleImage { get; set; }

    public string Description { get; set; }

    public Nullable<int> ModulId { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }



    public virtual ModuleMaster ModuleMaster { get; set; }

    public virtual ICollection<UserModuleImage> UserModuleImages { get; set; }

}

}
