
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sculptor.Gynac.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class RatingMaster
{

    public RatingMaster()
    {

        this.UserRatings = new HashSet<UserRating>();

    }


    public int Id { get; set; }

    public string RatingName { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }



    public virtual ICollection<UserRating> UserRatings { get; set; }

}

}
