
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sculptor.Gynac.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class UserRating
{

    public int UserRatingId { get; set; }

    public int UserId { get; set; }

    public int RatId { get; set; }

    public Nullable<int> RateMark { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public Nullable<int> TalkId { get; set; }



    public virtual RatingMaster RatingMaster { get; set; }

}

}
