
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sculptor.Gynac.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class User_Course
{

    public int User_Course_Id { get; set; }

    public int User_Id { get; set; }

    public int Course_Id { get; set; }

    public System.DateTime Registered_Date { get; set; }

    public Nullable<System.DateTime> Registered_Till { get; set; }

    public string Payment_Mode { get; set; }

    public Nullable<decimal> Payment_Amount { get; set; }

    public string Payment_Currency { get; set; }

    public bool Is_Active { get; set; }

    public string Transaction_Id { get; set; }

    public string Transaction_Status { get; set; }

    public string Order_Status { get; set; }



    public virtual Course Course { get; set; }

    public virtual User User { get; set; }

}

}
